# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'AG Solutions'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.PNG'
- name: LOGO
  value: '/brand-assets/logo.PNG'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.PNG'
- name: BRAND_URL
  value: 'https://dashboard.ag-solutions.tech'
- name: WIDGET_BRAND_URL
  value: 'https://dashboard.ag-solutions.tech'
- name: BRAND_NAME
  value: 'AG Solutions'
- name: TERMS_URL
  value: 'https://dashboard.ag-solutions.tech/terms-of-service'
- name: PRIVACY_URL
  value: 'https://dashboard.ag-solutions.tech/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #
